### ISSUE TITLE
disappearing images

### ISSUE THREAD

**Issue by vivkay** [vivkay/fw-silent-auction#1]
Hi @thomasjbradley, 

I have some disappearing images! They work wonderfully locally, with terminal. But for some reason, the images aren't going up to GitHub. 

This is what I'm seeing in terminal:

![screen shot 2016-02-12 at 8 52 49 pm](https://cloud.githubusercontent.com/assets/6340292/13024922/ff006e4a-d1ca-11e5-9de1-da04cf7d2974.png)

This is what I see at the Github Link after synching:

![screen shot 2016-02-12 at 8 52 56 pm](https://cloud.githubusercontent.com/assets/6340292/13024946/35a0442a-d1cb-11e5-89b4-e6c160f5c05b.png)

When I inspect them in the browser (from github), it says they are 0x20px. But when I try to add a height, nothing seems to happen. I'm confused as to why they would work so well on the localhost, and not on git? They are PNG's - each under about 50KB. Any ideas?

Thanks!

V

**Comment by thomasjbradley** [comment]
They're missing `{{site.baseurl}}` in front of their URLs. And, the `baseurl` inside `_config.yml` doesn't match your GitHub repo name.

**Comment by vivkay** [comment]
Perfecto! Thank you! :grinning:
